POST http://localhost:3000/blog
Content-Type: application/json

{
    "title": "Testing",
    "description": "Another blog post for you!",
    "blogBody": "Lorem lorem lorem"
}

###
GET http://localhost:3000/blog

###

PUT http://localhost:3000/blog/e8b9b67e-8ba4-4d8c-a7d7-c2c07be1f7eb
Content-Type: application/json

{
    "title": "Using AI to improve performance",
    "description": "Let's learn AI",
    "blogBody": "Lorem lorem lorem lorem lorem"

}

###

DELETE http://localhost:3000/blog/430e592b-7762-4829-9b06-c60e5e29d3d5